### ISSUE TITLE
[installation of pytorch lightning] pip install --editable .

### ISSUE THREAD

**Issue by alice-cool** [showlab/CLVQA#3]
![image](https://user-images.githubusercontent.com/16870890/220512091-40bac92c-7eec-4bfe-aff0-44cbe98de9fd.png)

**Comment by StanLei52** [comment]
Hi, thanks for pointing this out.

It seems that this pl version is outdated. You can directly install `pytorch-lightning==1.6.0` by changing the requirement file of mmf/mmclvqa [here](https://github.com/showlab/CLVQA/blob/d831f9a20fd37cbf724cd4a9e35e225b583a0b84/mmclvqa/requirements.txt#L21) .

**Comment by alice-cool** [comment]
这个版本也会让环境安装好
pycocotools==2.0.6
